name: RBAC CE CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'rbac/ce/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'rbac/ce/**'

permissions:
  contents: read

env:
  DOCKER_BUILDKIT: "1"

jobs:
  # Equivalent to "RBAC CE: Provision Test Image"
  provision-test-image:
    name: "RBAC CE: Provision Test Image"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rbac/ce
    env:
      MIX_ENV: test
    steps:
    - uses: actions/checkout@v4
    - name: Build test image
      run: |
        make build
        make push

  # Equivalent to "RBAC CE: Provision Prod Image"  
  provision-prod-image:
    name: "RBAC CE: Provision Prod Image"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rbac/ce
    env:
      MIX_ENV: prod
    steps:
    - uses: actions/checkout@v4
    - name: Build prod image
      run: |
        make pull
        make build
        make push

  # Equivalent to "RBAC CE: QA"
  qa:
    name: "RBAC CE: QA"
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3.8-management
        env:
          RABBITMQ_DEFAULT_USER: admin
          RABBITMQ_DEFAULT_PASS: admin
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 5
        ports:
          - 5672:5672    # AMQP port
          - 15672:15672  # Management UI port
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_DB: rbac_ce
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    needs: provision-test-image
    defaults:
      run:
        working-directory: rbac/ce
    env:
      MIX_ENV: test
    strategy:
      matrix:
        # Parallelism: 2 equivalent
        partition: [1, 2]
    steps:
    - uses: actions/checkout@v4
    - name: Build for QA
      run: make build
    - name: Lint
      run: make format.ex
    - name: Credo
      run: make lint.ex
    - name: Test
      run: |
        export TEST_RESULTS_NAME="RBAC CE Tests"
        make test.ex
      env:
        # Pass partition info if your tests support it
        TEST_PARTITION: ${{ matrix.partition }}

  # Equivalent to "RBAC CE: Deployment Preconditions"
  deployment-preconditions:
    name: "RBAC CE: Deployment Preconditions" 
    runs-on: ubuntu-latest
    needs: provision-prod-image
    defaults:
      run:
        working-directory: rbac/ce
    env:
      MIX_ENV: prod
      SERVICE_NAME: "RBAC CE"
    steps:
    - uses: actions/checkout@v4
    - name: Pull images
      run: make pull
    - name: Check code
      run: make check.ex.code
    - name: Check dependencies  
      run: make check.ex.deps
    - name: Check docker
      run: |
        make build
        make check.docker
